---
apiVersion: config.istio.io/v1alpha2
kind: QuotaSpec
metadata:
  name: request-count
  namespace: istio-system
spec:
  rules:
    - quotas:
        - charge: 1
          quota: requestcountquota
---
apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  name: quota-qps5
  namespace: istio-system
spec:
  compiledAdapter: memquota
  params:
    quotas:
      - name: requestcountquota.instance.istio-system
        maxAmount: 5
        validDuration: 1s
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: quota-qps5
  namespace: istio-system
spec:
  actions:
    - handler: quota-qps5
      instances:
        - requestcountquota